---
title: "감정분석"
output: html_document
---

### 01. 라이브러리 준비
```{r}
rm(list=ls())
library(wordcloud)
library(KoNLP)
```


### 02. 사전 불러오기
```{r}
useSejongDic()
fname = "C:\\Users\\SIT302-007\\Documents\\R\\R_data\\30_AgainCourt.txt"
road1 = readLines(fname)
```

### 03. 단어 사전 준비
```{r}
pos.words = scan("C:\\Users\\SIT302-007\\Documents\\R\\R_data\\pos_kor_words.txt", what="character", comment.char=";")
neg.words = scan("C:\\Users\\SIT302-007\\Documents\\R\\R_data\\neg_kor_words.txt", what="character", comment.char=";")
```

### 04. 텍스트 전처리
```{r}
require(plyr)
require(stringr)

sentence <- road1

# 구두점 문자, ! " # $ % & ’ ( ) * + , - . / : ; < = > ? @ [  ] ^ _ ` { | } ~. 제거
sentence <- gsub('[[:punct:]]', "", sentence)  
# \n, \r 같은 제어문자 등 제거
sentence <- gsub('[[:cntrl:]]', "", sentence)
# 숫자 제거
sentence <- gsub('\\d+', "", sentence)
head(sentence)
length(sentence)
```

### 05. 명사 추출
```{r}
# ,autoSpacing = TRUE
#### 명사 추출
wordlist <- sapply(sentence, extractNoun, USE.NAMES=F)
words <- unlist(wordlist)   # 단어를 하나의 벡터로 
head(words)

```


### 06. 점수 확인
```{r}
pos.matches <- match(words, pos.words)  ## 긍정단어, 부정단어 확인
neg.matches <- match(words, neg.words)  ## 단어 존재(사전에서 위치), 없으면 NA
pos.matches <- !is.na(pos.matches)  # NA가 아닌것 가져오기(문장에 단어 있음)
neg.matches <- !is.na(neg.matches)
sum(pos.matches)  # 점수 합(긍정단어)
score <- sum(pos.matches) - sum(neg.matches)


pos_word <- words[pos.matches ]
neg_word <- words[neg.matches ]

pos_cnt <- table(pos_word)
neg_cnt <- table(neg_word)

pos_cnt_sort <- sort(pos_cnt, decreasing = T)
neg_cnt_sort <- sort(neg_cnt, decreasing = T)

```

### 07. 긍정단어, 부정단어 TOP 5

## TOP 5 단어 그래프 보기
```{r}
barplot(pos_cnt_sort[5:0], main='긍정 단어 TOP 5', horiz=T, col=c("green", "blue", "yellow"))
```


```{r}
barplot(neg_cnt_sort[5:0], main="부정 단어 TOP 5", horiz=T, col=c("green", "blue", "yellow"))
```

### 08. 워드 클라우드

```{r}
library(wordcloud2)
pal <- brewer.pal(8, "Dark2")

base_word2 <- as.data.frame(pos_cnt, stringsAsFactors = F)
wordcloud2(data=base_word2, fontFamily = '나눔바른고딕')
```



